export {
  resolveAgentWorkspaceRoot,
  resolveAgentPrivilegesRoot,
  resolveSessionWorkspaceRoot,
  resolveSharedWorkspaceRoot,
  resolveSessionStateRoot,
  resolveSessionStateDir,
  assertSafeSessionId,
  migrateLegacyWorkspaceFiles,
  deleteSessionWorkspaceDirectory,
  deleteSessionStateDirectory,
  pruneOrphanSessionState,
  DEFAULT_ROOT_ID,
  SHARED_ROOT_ID,
  SESSIONS_SUBDIR,
  SHARED_SUBDIR,
  LEGACY_SUBDIR,
  SESSION_STATE_SUBDIR,
} from './paths.js'
export {
  ensureSharedWorkspaceLayout,
  seedBuiltinSharedPackages,
  resolveBuiltinSharedPackageTemplateDir,
  resetSharedWorkspaceLayoutCacheForTests,
} from './shared-workspace.js'
export {
  pruneSharedWorkspace,
  isProtectedSharedRelative,
  DEFAULT_SHARED_WORKSPACE_MAX_AGE_MS,
  DEFAULT_SHARED_WORKSPACE_MAX_BYTES,
  type PruneSharedWorkspaceOptions,
  type PruneSharedWorkspaceResult,
} from './shared-prune.js'
export {
  WorkspaceError,
  PathEscapeError,
  DenyPathError,
  QuotaExceededError,
  SsrfBlockedError,
  ConfirmationRequiredError,
  NetworkInstallConfirmationRequiredError,
  NetworkEgressConfirmationRequiredError,
  ShellRunConfirmationRequiredError,
} from './errors.js'
export { buildGlobalDenyPaths, isPathDenied, isSensitiveRelPath, isWorkspaceRootPath } from './deny.js'
export {
  resolveSafePath,
  ensureDirectory,
  RELATIVE_PATH_CONTRACT_HINT,
} from './path-gate.js'
export {
  MOUNTS_SUBDIR,
  MAX_BROWSE_DIR_ENTRIES,
  MAX_BROWSE_REL_DEPTH,
  resolveMountsRoot,
  emptyMountsReason,
  listMountRoots,
  collectGrantAllowlistRootsSync,
  isGrantPathAllowlisted,
  assertGrantPathAllowed,
  resolveBrowseRootAbs,
  browseWorkspaceDirs,
  type WorkspaceMountRoot,
  type WorkspaceBrowseEntry,
  type WorkspaceBrowseResult,
  type AssertGrantPathOptions,
} from './mounts.js'
export { assertAllowedUrl, assertAllowedHost } from './ssrf.js'
export {
  GrantStore,
  assertReadable,
  assertWritable,
  type GrantMode,
  type WorkspaceGrant,
} from './grants.js'
export {
  StickyPolicyStore,
  CONFIRM_OPTIONS,
  DOOM_LOOP_CONFIRM_OPTIONS,
  parseConfirmChoice,
  type StickyOperation,
  type ConfirmChoice,
} from './ask-policy.js'
export {
  QuotaTracker,
  DEFAULT_WORKSPACE_QUOTA_BYTES,
  getFreeDiskBytes,
} from './quota.js'
export { httpFetch, type HttpFetchParams, type HttpFetchResult } from './http-fetch.js'
export { streamDownloadToFile, type DownloadParams } from './download.js'
export {
  getSandboxSettings,
  saveSandboxSettings,
  resetSandboxSettingsStoreForTests,
} from './sandbox-settings-store.js'
export {
  getPythonSettings,
  savePythonSettings,
  resetPythonSettingsStoreForTests,
} from './python-settings-store.js'
export {
  resolveNodeRuntime,
  resolveNpmCliJs,
  nodeRuntimeAllowReadPaths,
  usesElectronAsNodeArgv,
  NODE_BINARIES,
  NPM_BINARIES,
  type NodeActiveSource,
  type NpmActiveSource,
  type NodeRuntimeStatus,
} from './node/resolve-node.js'
export { resolveShellArgv, looksLikePythonBin, looksLikePipBin } from './shell/resolve-shell-argv.js'
export type { ResolveShellArgvResult } from './shell/resolve-shell-argv.js'
export { resolvePosixShellPath, SPAWN_ENOENT_HINT } from './shell/resolve-shell-bin.js'
export {
  FILE_ENOENT_HINT,
  resolveEnoentToolHint,
  appendRelativePathNudge,
} from './enoent-hints.js'
export {
  resolvePythonRuntime,
  parsePythonVersionParts,
  pickHighestPythonProbe,
  isWindowsPythonInstallDirName,
  buildWindowsPythonExeCandidates,
  type PythonActiveSource,
  type PythonRuntimeStatus,
  type PythonProbe,
  PYTHON_BINARIES,
  PIP_BINARIES,
} from './python/resolve-python.js'
export { getPythonPlatformStatus } from './python/python-platform-status.js'
export {
  toAgentPythonEnvView,
  type AgentPythonEnvView,
} from './python/agent-python-env-view.js'
export {
  probePipIndexUrls,
  resolvePreferredPipIndexUrl,
  getPreferredPipIndexUrlSync,
  getSortedPipIndexUrlsSync,
  invalidatePipMirrorCache,
  rotatePreferredPipMirror,
  isPipMirrorNetworkFailure,
  PIP_MIRROR_CACHE_TTL_MS,
  resetPipMirrorCacheForTests,
  readPipMirrorCacheFileForTests,
} from './python/pip-mirrors.js'
export {
  ensurePythonReady,
  resetEnsurePythonDepsForTests,
  setEnsurePythonDepsForTests,
  type EnsurePythonResult,
  type EnsurePythonStatus,
  type EnsurePythonDeps,
} from './python/ensure-python.js'
export {
  resolveBundledPythonRoot,
  seedBundledPythonIfNeeded,
  BUNDLED_PYTHON_MANIFEST,
  type BundledPythonManifest,
} from './python/bundled-python.js'
export {
  getPythonPlatformArtifact,
  listPythonPlatformArtifacts,
  pythonPlatformKeyFromTarget,
  PYTHON_RUNTIME_VERSION,
  type PythonPlatformArtifact,
} from './python/catalog.js'
export {
  materializePythonArtifact,
  pruneMinicondaStagedTree,
  pythonBinaryCandidates,
  linkPythonCurrent,
} from './python/installer.js'
export {
  WorkspaceService,
  getWorkspaceService,
  resetWorkspaceService,
  type ConfirmHandler,
  type WorkspaceServiceOptions,
} from './service.js'
export {
  clampGlobMaxResults,
  globPatternToRegExp,
  globWithinRoot,
  DEFAULT_GLOB_MAX_RESULTS,
  MAX_GLOB_MAX_RESULTS,
  type WorkspaceGlobResult,
} from './workspace-glob.js'
export {
  clampGrepMaxHits,
  clampContextLines,
  grepWithinRoot,
  DEFAULT_GREP_MAX_HITS,
  MAX_GREP_MAX_HITS,
  DEFAULT_GREP_MAX_FILE_BYTES,
  type GrepMatchMode,
  type WorkspaceGrepHit,
  type WorkspaceGrepParams,
  type WorkspaceGrepResult,
} from './workspace-grep.js'
export {
  runCodePreflight,
  runL0StaticOnly,
  DEFAULT_PREFLIGHT_LEVELS,
  detectLanguageFromPath,
  checkEncoding,
  checkNewlines,
  checkPlatformPathRules,
  parseRuffOutput,
  parseBiomeOutput,
  type CodePreflightResult,
  type CodePreflightParams,
  type PreflightCheck,
  type PreflightDiagnostic,
  type PreflightLanguage,
  type PreflightLanguageOpt,
  type PreflightLevel,
} from './code-preflight/index.js'
export {
  ShellRunner,
  applyPythonRuntimeToChildEnv,
  SessionNetworkEgressStore,
  SessionLanAccessStore,
  getSessionLanAccessStore,
  resetSessionLanAccessStoreForTests,
  isEffectiveLanAllowed,
  applySessionLanAskChoice,
  SESSION_LAN_ASK_OPTIONS,
  SessionSecretAccessStore,
  getSessionSecretAccessStore,
  resetSessionSecretAccessStoreForTests,
  applySessionSecretGrantChoice,
  SESSION_SECRET_GRANT_ASK_OPTIONS,
  redactSecretsInText,
  redactSecretsInUnknown,
  NetworkInstallStickyStore,
  NETWORK_EGRESS_CONFIRM_OPTIONS,
  parseNetworkEgressChoice,
  NETWORK_INSTALL_CONFIRM_OPTIONS,
  parseNetworkInstallChoice,
  hostFromNetworkInput,
  normalizeEgressHost,
  summarizeShellArgv,
  buildSandboxConfigFromGrants,
  buildSandboxConfigFromGrantPaths,
  win32SystemReadAllowPaths,
  pythonActiveAllowReadPaths,
  isWindowsAclStampForbidden,
  needsWindowsAclGrant,
  filterWindowsAclGrantPaths,
  finalizeFilesystemPathsForPlatform,
  windowsAclForbiddenRoots,
  assertAllowedShellArgv,
  assertPackageInstallPolicy,
  injectPipCertArgv,
  argvToCommandString,
  syncCommandStringFromManagedArgv,
  commandNeedsNetwork,
  commandMayNeedEgressConfirmation,
  extractExplicitHostsFromArgv,
  isNetworkDiagnosticCommand,
  parseDiagnosticTargetHost,
  parseCommandToArgv,
  resolveShellCommandInput,
  commandNeedsRealShell,
  shellWrapArgv,
  getSessionShellRuntime,
  resetSessionShellRuntimeForTests,
  hashSandboxConfig,
  SessionShellRuntime,
  mergeAllowedNetworkDomains,
  networkDomainsForInstallAllowed,
  networkDomainsForDiagnosticTarget,
  networkDomainsForSessionHost,
  hostPatternsFromHttpsUrls,
  formatNetworkInstallConfirmPrompt,
  getGrantableMergedAllowedDomains,
  getGrantableMergedAllowedDomainsSync,
  getMergedRawAllowedDomains,
  getConfiguredAllowedDomains,
  getGrantableConfiguredAllowedDomains,
  getGrantableConfiguredAllowedDomainsSync,
  isHostInConfiguredAllowlist,
  isEgressHostPreAuthorized,
  resetConfiguredAllowedDomainsForTests,
  getShellPlatformStatus,
  resolveShellIsolationMode,
  isDockerEnv,
  resolveAgentSandboxMode,
  resolveDockerAgentIdentity,
  resolveDockerAgentDropIds,
  maybeChownForDockerAgent,
  isUnderDockerAgentWritableTree,
  DOCKER_PERSISTENCE_NOTE,
  PACKAGE_INSTALL_ALLOWED_DOMAINS,
  SRT_SUPPORTS_ALLOW_ALL_IN_ALLOWED_DOMAINS,
  resolveBundledCaCertPath,
  materializeBundledCaCert,
  applyBundledCaCertEnv,
  clearBundledCaCertEnv,
  bundledCaCertAllowReadPaths,
  detectNetworkEgressBlocked,
  buildNeedsNetworkEgressPayload,
  isRefreshableWindowsCredError,
  collectSandboxFailureText,
  withElevatedCredRefreshRetryOnThrow,
  withElevatedCredRefreshRetryOnResult,
  WIN_ERROR_LOGON_FAILURE,
  WIN_ERROR_NO_SUCH_LOGON_SESSION,
  assertUnelevatedRejectsFullNetworkIsolation,
  spawnUnelevatedRestricted,
  isUnelevatedSpawnSupported,
  probeRestrictedTokenApi,
  UNELEVATED_FULL_NETWORK_REJECT_MESSAGE,
  UNELEVATED_COMPONENT_UNAVAILABLE_MESSAGE,
  UNELEVATED_SPAWN_FAILED_MESSAGE,
  UNELEVATED_INTERNAL_ERROR_MESSAGE,
  allocStruct,
  getWinApis,
  tryLoadKoffi,
  resetUnelevatedProbeCacheForTests,
  ensureWindowsSandboxReady,
  isWindowsSandboxProvisioned,
  resetWindowsSandboxAutoInstallAttempt,
  type ShellRunParams,
  type ShellRunResult,
  type ShellBackgroundStartResult,
  type ShellInstallParams,
  type ShellPlatformStatus,
  type ShellPythonRuntimeInfo,
  type ShellSecretRef,
  type ShellIsolation,
  type ShellEscalate,
  type OpptrixShellIsolationMode,
  type NetworkInstallPreflightResult,
  type NetworkEgressPreflightResult,
  startShellCommandJob,
  getShellCommandJob,
  subscribeShellCommandJob,
  cancelShellCommandJob,
  clearSessionShellCommandJobs,
  resetShellCommandJobsForTests,
  isShellBgEnabled,
  clampShellBgTimeoutMs,
  countInFlightShellBgForSession,
  SHELL_BG_DEFAULT_TIMEOUT_MS,
  SHELL_BG_MAX_IN_FLIGHT_PER_SESSION,
  type ShellCommandJobSnapshot,
  type ShellCommandJobState,
  isHostInPackageInstallAllowlist,
  hostMatchesDomainPatterns,
} from './shell/index.js'
export {
  normalizeWorkspaceTextContent,
  decodeWorkspaceText,
  encodeWorkspaceText,
  detectWorkspaceEol,
  WORKSPACE_TEXT_ENCODING_HINT,
  WorkspaceTextEncodingError,
  type WorkspaceEol,
  type DecodedWorkspaceText,
} from './workspace-text.js'
export {
  applyLineEdits,
  applyExactReplace,
  assertExactReplaceOk,
  splitContentLines,
  joinContentLines,
  MAX_LINE_EDITS,
  MAX_NUMBERED_SNIPPETS_CHARS,
  type LineEditInput,
  type LineEditStatus,
  type LineEditResultItem,
  type NumberedSnippet,
  type ApplyLineEditsResult,
  type ExactReplaceResult,
} from './line-edit/index.js'
export {
  parseOpenCodePatch,
  applyUpdateHunks,
  applyParsedPatch,
  applyOpenCodePatchText,
  type PatchFileOp,
  type PatchHunk,
  type ParsedPatch,
  type ApplyPatchFileResult,
  type ApplyPatchResult,
  type ApplyPatchIo,
} from './apply-patch.js'
