/** aaashare Capability enum — data dimension identifiers */
export enum Capability {
  STOCK_REALTIME = 'stock_realtime',
  STOCK_KLINE = 'stock_kline',
  STOCK_MONEY_FLOW = 'stock_money_flow',
  INDEX_REALTIME = 'index_realtime',
  INDEX_KLINE = 'index_kline',
  MARKET_MONEY_FLOW = 'market_money_flow',
  SECTOR_MONEY_FLOW = 'sector_money_flow',
  SECTOR_LIST = 'sector_list',
  STOCK_BASIC = 'stock_basic',
  STOCK_PROFILE = 'stock_profile',
  SHAREHOLDER = 'shareholder',
  FINANCIAL_SUMMARY = 'financial_summary',
  NEWS = 'news',
  SENTIMENT = 'sentiment',
  DRAGON_TIGER = 'dragon_tiger',
  MARGIN_TRADE = 'margin_trade',
  DIVIDEND = 'dividend',
  BALANCE_SHEET = 'balance_sheet',
  INCOME_STMT = 'income_statement',
  CASH_FLOW = 'cash_flow',
  INST_HOLDING = 'inst_holding',
  BLOCK_TRADE = 'block_trade',
  LOCKUP_EXPIRY = 'lockup_expiry',
  SHARE_PLEDGE = 'share_pledge',
  INTRADAY_TICK = 'intraday_tick',
  STOCK_LIST = 'stock_list',
  INSTRUMENT_SEARCH = 'instrument_search',
  INDEX_CONST = 'index_constituent',
  INSIDER_TRADE = 'insider_trade',
  PERF_FORECAST = 'performance_forecast',
  TRADE_CALENDAR = 'trade_calendar',
  LIMIT_UPDOWN = 'limit_updown',
  MARKET_BREADTH = 'market_breadth',
  IPO_DATA = 'ipo_data',
  CONVERTIBLE_BOND = 'convertible_bond',
  ETF_DATA = 'etf_data',
  ETF_LIST = 'etf_list',
  ETF_PROFILE = 'etf_profile',
  ETF_HOLDINGS = 'etf_holdings',
  ETF_NAV = 'etf_nav',
  FUND_LIST = 'fund_list',
  FUND_PROFILE = 'fund_profile',
  FUND_NAV = 'fund_nav',
  FUND_HOLDINGS = 'fund_holdings',
  FUND_QUOTE = 'fund_quote',
  FUND_RETURNS = 'fund_returns',
  FUND_DRAWDOWN = 'fund_drawdown',
  FUND_ALLOCATION = 'fund_allocation',
  FUND_HOLDERS = 'fund_holders',
  FUND_DIVIDEND = 'fund_dividend',
  FUND_MANAGER = 'fund_manager',
  FUND_DIAGNOSIS = 'fund_diagnosis',
  FUND_NEWS = 'fund_news',
  FUND_FINANCIALS = 'fund_financials',
  MANAGER_INFO = 'manager_info',
  SHAREHOLDER_PLAN = 'shareholder_plan',
  BUYBACK = 'buyback',
  GLOBAL_INDEX = 'global_index',
  EXCHANGE_RATE = 'exchange_rate',
  MACRO_INDICATOR = 'macro_indicator',
  TECH_INDICATOR = 'tech_indicator',
  MAIN_BUSINESS = 'main_business',
  TOP_CUSTOMER = 'top_customer',
  ACTUAL_CONTROLLER = 'actual_controller',
  SUBSIDIARY = 'subsidiary',
  RELATED_PARTY = 'related_party',
  RD_INVESTMENT = 'rd_investment',
  MERGER_ACQUISITION = 'merger_acquisition',
  EMPLOYEE_COMP = 'employee_composition',
  INSTITUTIONAL_VISIT = 'institutional_visit',
  PEER_COMPANY = 'peer_company',
  CHIP_DISTRIBUTION = 'chip_distribution',
  /** ── v3：原自定义方法升级为系统标准能力（市场级，无单标的 ref）── */
  INDEX_CATALOG = 'index_catalog',
  INDEX_PRICES_SNAPSHOT = 'index_prices_snapshot',
  INDEX_CONSTITUENTS_RAW = 'index_constituents_raw',
  FINANCIAL_INDICATORS = 'financial_indicators',
  VALUATIONS_SNAPSHOT = 'valuations_snapshot',
  LIMIT_UP_LADDER = 'limit_up_ladder',
  SKYROCKET_LIST = 'skyrocket_list',
  HOT_STOCK_LIST = 'hot_stock_list',
  HOT_STOCK_LIST_HISTORY = 'hot_stock_list_history',
  HOT_STOCK_RANK_TREND = 'hot_stock_rank_trend',
  ANOMALY_ANALYSIS_LIST = 'anomaly_analysis_list',
  ANOMALY_ANALYSIS_STOCK = 'anomaly_analysis_stock',
  LIMIT_BREAK_POOL = 'limit_break_pool',
  AUCTION_SNAPSHOT = 'auction_snapshot',
  AUCTION_SHORT_TERM_BENCHMARK = 'auction_short_term_benchmark',
  FUND_COMPANY = 'fund_company',
  FUND_DIVIDEND_RAW = 'fund_dividend_raw',
  FUND_DAILY = 'fund_daily',
  FUND_ADJ = 'fund_adj',
  FUND_BASIC = 'fund_basic',
  FUND_NAV_RAW = 'fund_nav_raw',
  SHAREHOLDER_NUM = 'shareholder_num',
  MARKET_DEPTH = 'market_depth',
  MARKET_DEPTH_BATCH = 'market_depth_batch',
  UNIVERSE_LIST = 'universe_list',
  UNIVERSE_GET = 'universe_get',
  UNIVERSE_BATCH = 'universe_batch',
  EX_FACTOR = 'ex_factor',
  KLINE_BATCH = 'kline_batch',
  QUOTES_UNIVERSE = 'quotes_universe',
  KLINE_INTRADAY = 'kline_intraday',
  INTRADAY_BATCH = 'intraday_batch',
  /** ── v3.5：引擎复合能力（实现为引擎方法，不经单 driver 反射、无 provider binding）── */
  REALTIME_BATCH = 'realtime_batch',
  INTRADAY_SESSIONS = 'intraday_sessions',
}

/** Maps capability → cache type key (mirrors Python CACHE_TYPE) */
export const CACHE_TYPE: Partial<Record<Capability, string>> = {
  [Capability.STOCK_REALTIME]: 'stock_realtime',
  [Capability.STOCK_KLINE]: 'stock_kline',
  [Capability.STOCK_MONEY_FLOW]: 'stock_money_flow',
  [Capability.INDEX_REALTIME]: 'index_realtime',
  [Capability.INDEX_KLINE]: 'index_kline',
  [Capability.MARKET_MONEY_FLOW]: 'market_money_flow',
  [Capability.SECTOR_MONEY_FLOW]: 'sector_money_flow',
  [Capability.STOCK_PROFILE]: 'stock_profile',
  [Capability.FINANCIAL_SUMMARY]: 'financial_summary',
  [Capability.BALANCE_SHEET]: 'balance_sheet',
  [Capability.INCOME_STMT]: 'income_statement',
  [Capability.CASH_FLOW]: 'cash_flow',
  [Capability.SHAREHOLDER]: 'shareholder',
  [Capability.DIVIDEND]: 'dividend',
  [Capability.NEWS]: 'news',
  [Capability.SENTIMENT]: 'sentiment',
  [Capability.STOCK_LIST]: 'stock_list',
  [Capability.INSTRUMENT_SEARCH]: 'instrument_search',
  [Capability.ETF_PROFILE]: 'etf_profile',
  [Capability.ETF_NAV]: 'etf_nav',
  [Capability.ETF_HOLDINGS]: 'etf_holdings',
  [Capability.FUND_PROFILE]: 'fund_profile',
  [Capability.FUND_NAV]: 'fund_nav',
  [Capability.FUND_HOLDINGS]: 'fund_holdings',
  [Capability.FUND_QUOTE]: 'fund_quote',
  [Capability.FUND_RETURNS]: 'fund_returns',
  [Capability.FUND_DRAWDOWN]: 'fund_drawdown',
  [Capability.FUND_ALLOCATION]: 'fund_allocation',
  [Capability.FUND_HOLDERS]: 'fund_holders',
  [Capability.FUND_DIVIDEND]: 'fund_dividend',
  [Capability.FUND_MANAGER]: 'fund_manager',
  [Capability.FUND_DIAGNOSIS]: 'fund_diagnosis',
  [Capability.FUND_NEWS]: 'fund_news',
  [Capability.FUND_FINANCIALS]: 'fund_financials',
  [Capability.INDEX_CATALOG]: 'index_catalog',
  [Capability.INDEX_PRICES_SNAPSHOT]: 'index_prices_snapshot',
  [Capability.INDEX_CONSTITUENTS_RAW]: 'index_constituents_raw',
  [Capability.FINANCIAL_INDICATORS]: 'financial_indicators',
  [Capability.VALUATIONS_SNAPSHOT]: 'valuations_snapshot',
  [Capability.LIMIT_UP_LADDER]: 'limit_up_ladder',
  [Capability.SKYROCKET_LIST]: 'skyrocket_list',
  [Capability.HOT_STOCK_LIST]: 'hot_stock_list',
  [Capability.HOT_STOCK_LIST_HISTORY]: 'hot_stock_list_history',
  [Capability.HOT_STOCK_RANK_TREND]: 'hot_stock_rank_trend',
  [Capability.ANOMALY_ANALYSIS_LIST]: 'anomaly_analysis_list',
  [Capability.ANOMALY_ANALYSIS_STOCK]: 'anomaly_analysis_stock',
  [Capability.LIMIT_BREAK_POOL]: 'limit_break_pool',
  [Capability.AUCTION_SNAPSHOT]: 'auction_snapshot',
  [Capability.AUCTION_SHORT_TERM_BENCHMARK]: 'auction_short_term_benchmark',
  [Capability.FUND_COMPANY]: 'fund_company',
  [Capability.FUND_DIVIDEND_RAW]: 'fund_dividend_raw',
  [Capability.FUND_DAILY]: 'fund_daily',
  [Capability.FUND_ADJ]: 'fund_adj',
  [Capability.FUND_BASIC]: 'fund_basic',
  [Capability.FUND_NAV_RAW]: 'fund_nav_raw',
  [Capability.SHAREHOLDER_NUM]: 'shareholder_num',
  [Capability.MARKET_DEPTH]: 'market_depth',
  [Capability.MARKET_DEPTH_BATCH]: 'market_depth_batch',
  [Capability.UNIVERSE_LIST]: 'universe_list',
  [Capability.UNIVERSE_GET]: 'universe_get',
  [Capability.UNIVERSE_BATCH]: 'universe_batch',
  [Capability.EX_FACTOR]: 'ex_factor',
  [Capability.KLINE_BATCH]: 'kline_batch',
  [Capability.QUOTES_UNIVERSE]: 'quotes_universe',
  [Capability.KLINE_INTRADAY]: 'kline_intraday',
  [Capability.INTRADAY_BATCH]: 'intraday_batch',
}
